site:
  title: Test Circle CI docs
  url: https://daniloarcidiacono.github.io/test-circle-ci
  start_page: main-component::index.adoc

content:
  sources:
    # This excludes the git worktree from Antora's purview
    # When CircleCI checks out a specific tag, leaves the HEAD in a detached state
    # Without excluding the git worktree from Antora, the build fails due to duplicate files
    - url: ./.git
      branches:
        - master
        - support/*
      start_path: main-component

asciidoc:
  attributes:
    linkattrs: ''
    toc: ~

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  destinations:
    - provider: fs
      clean: true
    - provider: archive